all:
  io_object_chooser:
    filter:
      default:
        enable: false
        # fields:
        #   - title
        #   - description
    add_new:
      default:
        enable: false
      # Model:
      #   enable: true
      #   module: model_module
      #   action: new
