all:
  io_object_chooser:
    filter:
      default:
        enable: false
        # fields:
        #   - title
        #   - description
    add_new:
      default:
        enable: false
      ioGridItemImage:
        enable: true
        module: io_grid_item_image
        action: new