io_object_chooser_index:
  url: /io_object_chooser/:model
  class: sfRequestRoute
  param:
    module: ioObjectChooser
    action: index
  requirements:
    sf_method: get
    
io_object_chooser_show:
  url: /io_object_chooser/:model/show
  class: sfRequestRoute
  param:
    module: ioObjectChooser
    action: show
  requirements:
    sf_method: get

io_object_chooser_new:
  url: /io_object_chooser/:model/new
  class: sfRequestRoute
  param:
    module: ioObjectChooser
    action: new
  requirements:
    sf_method: get

